name: GetScreen Windows (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        shell: pwsh
        run: |
          echo "EMAIL_SECRET=wajufo.polkaroad@proton.me" | Out-File -FilePath "secrets.txt" -Encoding utf8
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/gdzoens68gz1o4wuwtf0x/down.bat?rlkey=wd1ecn33dv9yn2uvdyynavbs6&dl=1" -OutFile "down.bat"
          Get-Content down.bat # Display the content of the batch file
          # Optionally execute if needed
          # cmd /c down.bat || { Write-Host "Batch file failed to execute"; exit 1 }

      - name: Check for time.py
        run: |
          if (Test-Path -Path "time.py") {
            Write-Host "time.py exists."
          } else {
            Write-Host "time.py does not exist. Exiting."
            exit 1
          }

      - name: Run time.py
        run: python time.py
